title: EarthSpace Federation Archive
description: Story and universe archive of the ESF stories

# Build settings
markdown: kramdown
baseurl: "/esf"
permalink: pretty

include:
  - "*.html"
  - "*.md"

exclude_files:
  - esf.code-workspace
  - stories/story-adrenaline.md

exclude:
  - esf.code-workspace
  - stories/story-adrenaline.md
