title: EarthSpace Federation Archive
description: Story and universe archive of the ESF stories

remote_theme: "jekyll/minima@1e8a445"

exclude_files:
  - esf.code-workspace
  - story-adrenaline.md

exclude:
  - esf.code-workspace
  - story-adrenaline.md
